name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: zigmax809/metrics@latest
        with:
          file_name: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          config.timezone: Asia/Shanghai
          template: classic
          plugin_isocalendar: yes
          plugin_isocalendar.duration: half-year
          plugin_stars: yes
          plugin_stars.limit: 4
          plugin_followup: yes
          plugin_followup.sections: repositories
          plugin_followup.indepth: false
          plugin_base.indepth: false
          plugin_achievements: yes
          plugin_achievements.threshold: C
          plugin_achievements.secrets: true
          plugin_achievements.display: compact
          plugin_achievements.limit: 0
          plugin_pagespeed: yes
          plugin_pagespeed.url: https://www.zigma.cc
          plugin_pagespeed.detailed: false
          plugin_pagespeed.screenshot: false
